image: node:9.11.1

pages:
 cache:
   paths:
   - node_modules/

 script:
 - set -e
 - npm run docs:build
 - git init
 - git add -A
 - git commit -m 'deploy'
 - cd -
 artifacts:
   paths:
   - dist
 only:
 - master